lecture04課題
wombattakuya/AWS-Raisetech-practice2 pull request #11
Opened 2023-11-06 13:16 UTC by wombattakuya

lecture04の課題を提出します。よろしくお願いします。

2023-11-06 13:49 UTC, MasatoshiMizumoto requested changes
以下ご対応お願いします！！

1. スタイルが適用されていないので、このURLを見ながら全体的に見直しお願いしたいです！pushすれば数分で反映されるので見ながらやってください！　https://github.com/wombattakuya/AWS-Raisetech-practice2/blob/86b7d9f0ec746cb2daa5cbcc1497c75e88372409/lecture04_1106.md
2. 画像の添付のやり方がちょっと期待と異なるので別の方法でお願いします！コード一緒に送信して、GitHubからはプレビュー画面で見られるようにしてください！
3. 各種リソースの作成に成功したエビデンスも欲しいです！

2023-11-21 15:12 UTC, MasatoshiMizumoto requested changes
前より良くなってますが期待している内容と差があるのでコメントを読んでご対応ください！

2023-11-21 15:12 UTC, MasatoshiMizumoto commented on lecture04_1106.md
1）もう少しスタイリング踏み込んで欲しいです！
brタグはこんなに多用しなくとも、見出しやリストを使えば不要なので、見出し、本文、リストと授業で習ったはずなので使ってください！

2）画像はmarkdownと同じ場所にpushしたのであれば、相対Pathで書けるはずで、Issueにアップするのは不要です！修正お願いします！

2023-11-21 15:39 UTC, wombattakuya commented on lecture04_1106.md
確認ありがとうございます。
1)　「-」で改行して修正しました。

2） 相対パスで書くには
　　![名前](名前.PNG)
　　だと調べて記述しましたが、違う方法で相対パスを書くのでしょうか。
よろしくお願いします。

2023-11-21 15:41 UTC, wombattakuya commented on lecture04_1106.md
2)について
　相対パスでは　/　/　で区切りながら記述していく方法になりますか。

2023-11-21 16:07 UTC, merged